apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml -o template
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: gogs
  name: gogs
spec:
  ports:
  - name: "10022"
    port: 10022
    targetPort: 22
  - name: "3000"
    port: 3000
    targetPort: 3000
  selector:
    io.kompose.service: gogs
status:
  loadBalancer: {}
